#!/bin/bash

# bspwm hotkeys

# quits bspwm
super + shift + Escape
	bspc quit

# launches dmenu2
alt + F2
	dmenu_launch

# quits the current active window
alt + F4
	bspc window -c

# toggles window to fullscreen
alt + enter
	bspc window -t fullscreen

# toggles window to floating
alt + space
	bspc window -t floating

# alt-tab
alt + {_,shift + }Tab
	bspc window -f {prev,next}

# defines a preselect
super + {Up,Down,Left,Right}
	bspc window --presel {up,down,left,right}

# moves around windows
alt + shift + {Up,Down,Left,Right}
	bspc window -s {up,down,left,right}

# resizes by 10px
super + shift + {Up,Down,Left,Right}
	bspc window -e {up +10,up -10,right -10,right +10}
super + alt + {Up,Down,Left,Right}
	bspc window -e {down +10,down -10,left -10,left +10}

# mouse movement and resizing
~button1
	bspc pointer -g focus
alt + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}
alt + !button{1-3}
	bspc pointer -t %i %i
alt + @button{1-3}
	bspc pointer -u

# media keys
XF86AudioRaiseVolume
	pulseaudio-ctl up 2
XF86AudioLowerVolume
	pulseaudio-ctl down 2
XF86AudioMute
	pulseaudio-ctl mute
XF86Audio{Play,Prev,Next,Stop}
	mpc -q {toggle,cdprev,next,stop}

# print screen
Print
	screenshot all
shift + Print
	screenshot region

# reloads everything
super + Escape
	pkill -USR1 -x sxhkd; \
	pkill -x lemonbar; \
	pkill -x compton; \
	pkill -x dunst; \
	bar; \
	dunst; \
	set_theme; \
	compton --config ~/.config/compton/config; \
	~/.config/bspwm/bspwmrc;
