#!/bin/bash

# bspwm hotkeys

# quits bspwm
super + shift + Escape
	bspc quit

# launches dmenu2
alt + F2
	dmenu_launch

# quits the current active window
alt + F4
	bspc window -c

# toggles window to fullscreen
alt + enter
	bspc window -t fullscreen

# toggles window to floating
alt + space
	bspc window -t floating

# alt-tab
alt + {_,shift + }Tab
	bspc window -f {prev,next}

# moves current window to another workspace
super + shift + {Left,Right}
	ACTIVE_WINDOW=$(bspc query -W -w focused); \
	CURRENT=$(bspc query -D -d focused); \
	ATTEMPTED=$(expr $CURRENT {-,+} 1); \
	if [ "$ATTEMPTED" -ge 4 ]; then \
		DESKTOP=1; \
	elif [ "$ATTEMPTED" -le 0 ]; then \
		DESKTOP=3; \
	else \
		DESKTOP=$ATTEMPTED; \
	fi; \
	bspc window -d $DESKTOP; \
	bspc desktop -f $DESKTOP; \
	bspc window -f $ACTIVE_WINDOW

# moves windows
super + {Up,Down,Left,Right}
	bspc window -s {up,down,left,right}

# preselects windows
super + {j,k,h,l}
	bspc window -p {up,down,left,right}

# balances, circulates, equalizes, flips, or rotates active desktop
super + {b,c,e,f,r}
	bspc desktop -{B,C forward,E,F vertical,R 90}

# ratios
super + {1,2,3}
	bspc window -e right {0.25,0.33,0.50}
super + {4,5,6}
	bspc window -e left {0.25,0.33,0.50}

# mouse movement and resizing
~button1
	bspc pointer -g focus
alt + button{1-3}
	bspc pointer -g {move,resize_corner,resize_side}
alt + !button{1-3}
	bspc pointer -t %i %i
alt + @button{1-3}
	bspc pointer -u

# media keys
XF86AudioRaiseVolume
	pulseaudio-ctl up 2
XF86AudioLowerVolume
	pulseaudio-ctl down 2
XF86AudioMute
	pulseaudio-ctl mute
XF86Audio{Play,Prev,Next,Stop}
	mpc -q {toggle,cdprev,next,stop}

# print screen
Print
	screenshot all
shift + Print
	screenshot region
ctrl + Print
	screenshot webm

# launches a terminal
super + grave
	urxvt

# lock the screen
super + l
	lockscreen

# reloads everything
super + Escape
	pkill -USR1 -x sxhkd; \
	pkill -x lemonbar; \
	pkill -x compton; \
	pkill -x dunst; \
	bar; \
	dunst; \
	set_theme; \
	compton --config ~/.config/compton/config; \
	~/.config/bspwm/bspwmrc;
