#!/bin/sh

source ~/.config/themerc

# Sizes of borders and spacing
bspc config border_width				2
bspc config window_gap					20

# Colors
bspc config focused_border_color		$COLOR_37
bspc config active_border_color			$COLOR_37
bspc config normal_border_color			$COLOR_37
bspc config urgent_border_color			$COLOR_37
bspc config presel_border_color			$COLOR_37

# General settings
bspc config split_ratio					1
bspc config borderless_monocle			false
bspc config gapless_monocle				false
bspc config focus_follows_pointer		false
bspc config auto_alternate				true
bspc config auto_cancel					true
bspc config normal_frame_opacity 		1
bspc config focused_frame_opacity 		1

# Monitor specific settings
bspc config -m DVI-D-0 top_padding		20
bspc config -m DVI-D-0 left_padding		20
bspc config -m DVI-D-0 right_padding	20
bspc config -m DVI-D-0 bottom_padding	20

bspc config -m DVI-I-1 top_padding		40
bspc config -m DVI-I-1 left_padding		20
bspc config -m DVI-I-1 right_padding	20
bspc config -m DVI-I-1 bottom_padding	20

bspc config -m DP-0 top_padding			20
bspc config -m DP-0 left_padding		20
bspc config -m DP-0 right_padding		20
bspc config -m DP-0 bottom_padding		20

# Desktop definitions
bspc monitor DVI-D-0 -d 1
bspc monitor DVI-I-1 -d 2
bspc monitor DP-0    -d 3

# Window rules
bspc rule -a "deluge"					floating=on
bspc rule -a "google-chrome-unstable (/home/bowan/.config/google-chrome-unstable)" 							desktop=^1 floating=off fullscreen=off
bspc rule -a "google-chrome-unstable" 	desktop=^1 floating=on fullscreen=off
bspc rule -a "mpv"						desktop=^1 floating=on center=on
bspc rule -a "pavucontrol"				floating=on
bspc rule -a "spacefm"					floating=on
bspc rule -a "speedcrunch"				floating=on
bspc rule -a "subl3"					desktop=^3
bspc rule -a "telegram"					desktop=^3
